Project setup
wolox-training/dc-swift pull request #2
Opened 2018-11-20 19:01 UTC by danielcharry

## Summary ##

**Trello card**: https://trello.com/c/vTPbpTfS/11-vista-de-biblioteca

View Library

2018-11-20 19:32 UTC, DiegoQuiros94 requested changes

2018-11-20 19:32 UTC, DiegoQuiros94 commented on DcProject/LibraryController.swift
> +
esta extension la podes borrar, ya no la estamos usando

2018-11-20 19:32 UTC, DiegoQuiros94 commented on DcProject/TabBarController.swift
> +        navigationView()
este nombre no me gusta mucho, no es muy descriptivo, yo le pondria setUpTabBarControllers o algo por el estilo

2018-11-20 19:32 UTC, DiegoQuiros94 commented on DcProject/TabBarController.swift
> +        libraryController.tabBarItem = UITabBarItem(title: "Library", image: UIImage(named: "library"), selectedImage: UIImage(named: "library"))
agrega el titulo a los localizables

2018-11-20 19:32 UTC, DiegoQuiros94 commented on DcProject/TabBarController.swift
> +        wishListController.tabBarItem = UITabBarItem(title: "WishList", image: UIImage(named: "wishlist"), selectedImage: UIImage(named: "wishlist"))
agrega el titulo a los localizables

2018-11-20 19:38 UTC, florenciarosental reviewed
Sumado a lo que dijo Diego, tene en cuenta esto para las proximas features que agregues. 
* La idea es que crees un nuevo branch por cada funcionalidad que hagas. Por lo tanto, el nombre de este branch debería ser algo tipo `library-view`. Es importante que cada branch se use para el desarrollo de una funcionalidad especifica. (Ahora no hace falta que cambies nada de esto, podes dejarlo asi. Pero tenelo en cuenta para la proxima funcionalidad).
* Lo mismo para el nombre del PR. Estaria bueno que sea un pequeño titulo de la funcionalidad que hiciste, algo como "Library View" en este caso.

2018-11-21 12:26 UTC, DiegoQuiros94 approved these changes

2018-11-21 13:16 UTC, merged